name: hexlet-ci-app
on: push
jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
      - uses: actions/setup-node@v2
        with: 
          node-version: '16.x'
          cashe: npm
      - run: make setup
      - run: make test
      - run: make lint
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}